# Input parameters
float64 distance
float64 linear_speed
float64 angular_speed
builtin_interfaces/Duration time_allowance

---

# Result definition
builtin_interfaces/Duration total_elapsed_time

---

# Feedback definition
float64 distance_traveled
float64 angle_rotated